// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARweX8nPpQMY-ZChIZNNWzRnss9MlwpjE',
    appId: '1:777227857742:web:bea9a64dd45dd84a51781f',
    messagingSenderId: '777227857742',
    projectId: 'online-payment-getaway',
    authDomain: 'online-payment-getaway.firebaseapp.com',
    storageBucket: 'online-payment-getaway.appspot.com',
    measurementId: 'G-6MDK8H4YJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYSq8CUWR2HKNHPDzu6QFriTu8AwGPBU4',
    appId: '1:777227857742:android:564e9fd04c3fb94251781f',
    messagingSenderId: '777227857742',
    projectId: 'online-payment-getaway',
    storageBucket: 'online-payment-getaway.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLKX2NKBUZAKT64PckNJUhadeANIVncM',
    appId: '1:777227857742:ios:88588244de82903751781f',
    messagingSenderId: '777227857742',
    projectId: 'online-payment-getaway',
    storageBucket: 'online-payment-getaway.appspot.com',
    iosClientId: '777227857742-nce76hockpu90khlcpqad0nfma32nkp9.apps.googleusercontent.com',
    iosBundleId: 'net.paykw.mobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLKX2NKBUZAKT64PckNJUhadeANIVncM',
    appId: '1:777227857742:ios:88588244de82903751781f',
    messagingSenderId: '777227857742',
    projectId: 'online-payment-getaway',
    storageBucket: 'online-payment-getaway.appspot.com',
    iosClientId: '777227857742-nce76hockpu90khlcpqad0nfma32nkp9.apps.googleusercontent.com',
    iosBundleId: 'net.paykw.mobapp',
  );
}
